//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopProject.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Product : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> PriceSale { get; set; }
        public Nullable<double> PriceImport { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        
        public virtual ICollection<Item> Item { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
